name: CeleScope

on: [push, pull_request]

jobs:
  setup_and_lint:
    strategy:
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # No shallow clone, we need all history!
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install
      run: |
        pip install celescope
        python setup.py install
        
        # test
        celescope -h

        # lint
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})
        for changed_file in $CHANGED_FILES; do
          if [[ $changed_file == *.py ]]
          then
            # W1618 (no-absolute-import)
            # E1101 (no-member)
            # W1633 (round-builtin)
            # W1619 (old-division)
            # W0105 (String statement has no effect)
            pylint --disable=all --enable=E,W --disable=W1618,E1101,W1633,W1619,W0105 $changed_file
          fi
        done

  
